First tests for pilot project
YosysHQ/yosys-tests pull request #1
Opened 2018-12-12 13:38 UTC by SergeyDegtyar

This tests are for the next task list:

For a pilot project there are couple of tasks.
1. FSM with unreachable state
On http://scratch.clifford.at/coverage_html/passes/fsm/fsm_opt.cc.gcov.html at line 56 it can be
seen that code never reach this part. Idea is to generate Verilog code that will contain states
that could not be reached.
2. Optimization of FSM when signal connected to input/input and output
On same code part starting line 166 and 204, it can be seen (painted in red) that optimization of
I/O signal usage in FSM is never reached
3. DFF with constant drivers
On http://scratch.clifford.at/coverage_html/passes/opt/opt_rmdff.cc.gcov.html at line 98, driving
DFF with constant, also line 154 for constant clear or constant set. Make Verilog code to reach
this states. Also cover DFF without reset
4. Tri-state buffers general use
Line 286 of http://scratch.clifford.at/coverage_html/passes/techmap/simplemap.cc.gcov.html
show that tri-state buffers were not used in any case, so creating some generic test would be
useful to cover this.
5. Tri-state buffers with constant
Line 721 of http://scratch.clifford.at/coverage_html/passes/opt/opt_expr.cc.gcov.html shows that
tri-state buffers with constant inputs need to covered.
6. Demoting I/O port
Demoting inout ports should be covered, shown at line 109 of
http://scratch.clifford.at/coverage_html/passes/techmap/deminout.cc.gcov.html
7. MACC cells
As seen at lines 113-341 of
http://scratch.clifford.at/coverage_html/passes/opt/share.cc.gcov.html no test is using macc cells
at all, task is to create test covering most of code in this file

2018-12-16 12:44 UTC, cliffordwolf requested changes
Thanks for your work. This is coming along nicely. Please see my review comments for requested changes.

2018-12-16 12:44 UTC, cliffordwolf commented on simple/dff/testbench.v
> +module assert(input clk, input test);
Since `assert` is a SystemVerilog keyword we should avoid it. Maybe let's call it something like `assert_expr` instead?

Also: since this is something we are re-using in many of the individual tests, maybe let's move it to a `yosys-tests/simple/common.v` file?

2018-12-16 12:44 UTC, cliffordwolf commented on simple/dff/testbench.v
> +            //$finish;
This `$finish` should actually be enabled to avoid printing `OKAY` at a later point of time. Otherwise `run.sh` will treat it as a passing test.

Furthermore, the error message should contain the string `ERROR`, as this is what `run.sh` uses to detect a failing test.

Finally, it would be even better to use `$stop` instead of `$finish` here, as this would result in the icarus verilog runtime (`vvp`) to exit with return code 1, indicating an error (`run.sh` uses `vvp -N`).

2018-12-16 12:44 UTC, cliffordwolf commented on simple/dff/testbench.v
> +		repeat (20000) #3 dinA = !dinA;
Code like this has race conditions with the other initial block that updates `clk`.

Also, mixing `<=` and `=` for the same variable is very bad style (and even forbidden in synthesizable code).

Better would be something like the following:

```
reg dinA;

initial begin
  dinA <= 0;
  always @(posedge clk) begin
    dinA <= !dinA;
  end
end
```

And even better:

```
reg dinA = 0;

always @(posedge clk) begin
  dinA <= !dinA;
end
```

2018-12-16 12:44 UTC, cliffordwolf commented on simple/dff/testbench.v
> +    );
The name `doutB` would be much better considering that `uut.b` is an output.

2018-12-16 12:44 UTC, cliffordwolf commented on simple/dffc/testbench.v
> +	end
Both of these initial blocks have the same race condition issues as described above. Much better would be something like the following:

```
reg dinA = 0;
reg dinB = 0;

always @(posedge clk) begin
  {dinA, dinB} <= {dinA, dinB} + 1;
end
```

Or even better, something like this:

```
function [31:0] xorshift32;
        input [31:0] arg;
        begin
                xorshift32 = arg;
                // Xorshift32 RNG, doi:10.18637/jss.v008.i14
                xorshift32 = xorshift32 ^ (xorshift32 << 13);
                xorshift32 = xorshift32 ^ (xorshift32 >> 17);
                xorshift32 = xorshift32 ^ (xorshift32 <<  5);
        end
endfunction

reg [31:0] rng = 123456789;
always @(posedge clk) rng <= xorshift32(rng);

wire dinA = xorshift32(rng * 5);
wire dinB = xorshift32(rng * 7);
```

2018-12-16 12:44 UTC, cliffordwolf commented on simple/macc/testbench.v
> +    end
Again, race conditions.

Better would be something like the following:

```
initial begin
  rst <= 0;

  @(posedge clk);

  rst <= 1;
  dinA <= 38;
  dinB <= 22;
  carryin <= 1;

  repeat (10) @(posedge clk);

  dinA <= 0;
  dinB <= 0;
  carryin <= 0;
  
  repeat (10) @(posedge clk);

  ....
end
```

2018-12-16 12:44 UTC, cliffordwolf commented on simple/Makefile
> +$(eval $(call template,dffsr, dff))
The `dff` doesn't really test a DFF. It only tests the special case of a DFF that has it's D input hard-wired to zero, and so forth. Maybe a more expressive name would be better. Maybe for example `dff_d0`.

2018-12-16 13:27 UTC, cliffordwolf commented
I've now also added a `falsify` test to `simple/alu`: Now the `alu` test design contains an `ifdef BUG` block that introduces incorrect behavior to the design that must be detected by the test bench. The `falsify` check (automatically added to all designs) now makes sure the testbench correctly identifies the design with bug.

Please add `ifdef BUG` blocks to your `top.v` files accordingly.

2018-12-17 09:58 UTC, SergeyDegtyar commented on simple/dff/testbench.v
> +module assert(input clk, input test);
"Also: since this is something we are re-using in many of the individual tests, maybe let's move it to a yosys-tests/simple/common.v file?"

Now all my "assert" modules are different in tests. Different checks, different amount of inputs and different types. Should I unify it for all tests, all move all variants to  yosys-tests/simple/common.v with different names?

2018-12-18 15:00 UTC, cliffordwolf commented on simple/dff/testbench.v
> +module assert(input clk, input test);
hmm... if not much would be shared then just leave it in the testbench file and simpy rename it to something like `<uut_name>_checker` instead of `assert`.

2019-01-02 15:06 UTC, merged

2019-01-02 15:15 UTC, cliffordwolf commented
Merged with some minor fixes (see 6dd772b).